# this is the basic configuration file, use cifar10 as default experiments
T: 2   # number of iterations (seeds)

run_batch_size: 40 # number of experiments to run in parallel

id_ds: 
  - 'cifar100'
methods: 
  - 'no-ucb'
  - 'hoeffding'
  - 'lil-heuristic'
  - 'tpr_95'
  - 'fpr_5'
scores: 
  - 'MDS'
alphas: 
  - 0.05
probs: 
  - 0.2  # importance sampling probability
deltas: 
  - 0.2
gamma: 
  - 0.2
window_sizes: 
  - null
  - 10000

change: True # if True, the change detection is performed

root_pfx: 'real' # the folder you are going to store under the output folder

# ------------------ below is the default configuration file ------------------
seed: 0
root_dir: '../'

data_conf: 
  simulation: False 
  streams: 
    - 
      name_id: 'cifar100'
      num_samples: 50000 
      gamma: 0.2
      name_ood: 'ood1'
      ood_method: 'KNN'
    - 
      name_id: 'cifar100'
      num_samples: 150000 
      gamma: 0.2
      name_ood: 'ood2'
      ood_method: 'KNN'

method: "lil-heuristic"
window: null
tpr_k: 95


alpha: 0.05 #the FPR tolerance
delta: 0.2 # the high probability of the confidence interval
prob: 0.2 #the probability of querying when the score is larger than the threshold

# change detection
detect_change: True # if True, the change detection is performed
restart: False      # if True, after change is detected, the sample pool is restarted
